sonar.projectKey=achrafkt_SiteTicket
sonar.organization=achrafkt

sonar.sources=backend/src,web/src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**,**/.next/**,backend/prisma/migrations/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,web/coverage/lcov.info
